services:
  init-data:
    image: busybox
    command: chown -R 65532:65532 /data && chmod -R 755 /data
    volumes:
      - dbdata:/data

  surrealdb:
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - rocksdb:/data/database.db
    image: surrealdb/surrealdb:v2.1
    ports:
      - 8000:8000
    volumes:
      - dbdata:/data
    networks:
      - db
    depends_on:
      - init-data

  meilisearch:
    image: getmeili/meilisearch:v1.13.0
    env_file:
      - .env
    ports:
      - 7700:7700
    volumes:
      - meili:/meili_data
    networks:
      - meili

  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 3000:3000
    networks:
      - meili
      - db
    depends_on:
      - surrealdb

networks:
  db:
  meili:

volumes:
  dbdata:
  meili: