services:
  init-data:
    image: busybox
    command: chown -R 65532:65532 /data && chmod -R 755 /data
    volumes:
      - dbdata:/data

  surrealdb:
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - rocksdb:/data/database.db
    image: surrealdb/surrealdb:v2.1
    ports:
      - 8000:8000
    volumes:
      - dbdata:/data

volumes:
  dbdata: