services:
  init-data:
    image: busybox
    command: chown -R 65532:65532 /data && chmod -R 755 /data
    volumes:
      - dbdata:/data

  surrealdb:
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - rocksdb:/data/database.db
    image: surrealdb/surrealdb:v2.1
    ports:
      - 8000:8000
    volumes:
      - dbdata:/data
    networks:
      - db
    depends_on:
      - init-data

  ollama:
    image: ollama/ollama:latest
    volumes:
      -  ollama:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh
    container_name: ollama
    restart: always
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]
    networks:
      - ollama

  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 3000:3000
    networks:
      - ollama
      - db
    depends_on:
      - surrealdb

networks:
  db:
  ollama:

volumes:
  dbdata:
  ollama: