/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as CollectionIdIndexImport } from "./routes/$collectionId/index";
import { Route as CollectionIdDocumentIdImport } from "./routes/$collectionId/$documentId";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const CollectionIdIndexRoute = CollectionIdIndexImport.update({
  id: "/$collectionId/",
  path: "/$collectionId/",
  getParentRoute: () => rootRoute,
} as any);

const CollectionIdDocumentIdRoute = CollectionIdDocumentIdImport.update({
  id: "/$collectionId/$documentId",
  path: "/$collectionId/$documentId",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/$collectionId/$documentId": {
      id: "/$collectionId/$documentId";
      path: "/$collectionId/$documentId";
      fullPath: "/$collectionId/$documentId";
      preLoaderRoute: typeof CollectionIdDocumentIdImport;
      parentRoute: typeof rootRoute;
    };
    "/$collectionId/": {
      id: "/$collectionId/";
      path: "/$collectionId";
      fullPath: "/$collectionId";
      preLoaderRoute: typeof CollectionIdIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$collectionId/$documentId": typeof CollectionIdDocumentIdRoute;
  "/$collectionId": typeof CollectionIdIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$collectionId/$documentId": typeof CollectionIdDocumentIdRoute;
  "/$collectionId": typeof CollectionIdIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/$collectionId/$documentId": typeof CollectionIdDocumentIdRoute;
  "/$collectionId/": typeof CollectionIdIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/$collectionId/$documentId" | "/$collectionId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/$collectionId/$documentId" | "/$collectionId";
  id: "__root__" | "/" | "/$collectionId/$documentId" | "/$collectionId/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CollectionIdDocumentIdRoute: typeof CollectionIdDocumentIdRoute;
  CollectionIdIndexRoute: typeof CollectionIdIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionIdDocumentIdRoute: CollectionIdDocumentIdRoute,
  CollectionIdIndexRoute: CollectionIdIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$collectionId/$documentId",
        "/$collectionId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$collectionId/$documentId": {
      "filePath": "$collectionId/$documentId.tsx"
    },
    "/$collectionId/": {
      "filePath": "$collectionId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
