/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as DocDocumentIdImport } from "./routes/doc/$documentId";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const DocDocumentIdRoute = DocDocumentIdImport.update({
  id: "/doc/$documentId",
  path: "/doc/$documentId",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/doc/$documentId": {
      id: "/doc/$documentId";
      path: "/doc/$documentId";
      fullPath: "/doc/$documentId";
      preLoaderRoute: typeof DocDocumentIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/doc/$documentId": typeof DocDocumentIdRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/doc/$documentId": typeof DocDocumentIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/doc/$documentId": typeof DocDocumentIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/doc/$documentId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/doc/$documentId";
  id: "__root__" | "/" | "/doc/$documentId";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DocDocumentIdRoute: typeof DocDocumentIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocDocumentIdRoute: DocDocumentIdRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/doc/$documentId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/doc/$documentId": {
      "filePath": "doc/$documentId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
